//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrUserAccess
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AccessControlId { get; set; }
        public string Right { get; set; }
    
        public virtual AccessControl AccessControl { get; set; }
        public virtual Users Users { get; set; }
    }
}
